In [2]:
## numpy는 다차원 배열 계산에 유리하다

In [3]:
data =7 # 0차원

In [5]:
my_list = [1,2,3,4,5] # 1차원 or 벡터(크기, 방향)

In [9]:
#파이썬의 1차원 배열 -> 리스트
import numpy as np

In [10]:
temp_list = [185.5,186.2,184.8,185.0,186.1]

In [14]:
temps=np.array (temp_list)  #리스트를 넘파이로 변환

In [15]:
temps.mean()

np.float64(185.52)

In [17]:
sensor_list=[[185.5,186.2,184.8],[120.3,121.5,119.8],[45.2,44.8,45.5]]

In [18]:
sensor_list

[[185.5, 186.2, 184.8], [120.3, 121.5, 119.8], [45.2, 44.8, 45.5]]

In [20]:
sensor_data= np.array(sensor_list)

In [21]:
#numpy로 만드는 방법 -> np.arrary()함수 사용

In [22]:
# 모든 값을 0으로 채운 배열 만들기

In [24]:
np.zeros(5) #1차원 배열

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((3,3)) #2차원 배열

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 모든 값을 1로 채우는 배열만들기

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
#모든 값을 특정값으로 채우는 방법

In [32]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [33]:
np.full((2,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [34]:
np.empty((2,3)) #아무 값이나 넣는 것

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.89146047e-307, 2.67018234e-306, 1.05699581e-307]])

In [35]:
temps.shape

(5,)

In [38]:
np.zeros_like(temps)  # shape은 유지하되 0d으로 채워라

array([0., 0., 0., 0., 0.])

In [40]:
np.ones_like(temps) # shape은 유지하되 0d으로 채워라

array([1., 1., 1., 1., 1.])

In [42]:
list(range(10)) # 0부터 9까지 정수 만들기

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
np.arange(10) #np로 0부터 9까지 만들기

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# 1부터 10까지

In [50]:
#np.linspace

In [51]:
time_axis = np.arange(0,3600,1)

In [52]:
#0~24시를 1시간 간격

In [54]:
np.linspace(0,24,25)  #처음값, 마지막값, 갯수

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [55]:
### 랜덤데이터 생성

In [56]:
# 0 ~ 1 사이의 균등 분포로 랜덤숫자 만들기

In [65]:
np.random.rand(5) #rand라는 숫자는 0~1사이의 숫자

array([0.78300361, 0.85032764, 0.77524489, 0.03666431, 0.11669374])

In [63]:
np.random.seed(20) # 시드값 만들기

In [64]:
np.random.rand(3,4)  # 2차원 배열로 랜덤 숫자 생성

array([[0.5881308 , 0.89771373, 0.89153073, 0.81583748],
       [0.03588959, 0.69175758, 0.37868094, 0.51851095],
       [0.65795147, 0.19385022, 0.2723164 , 0.71860593]])

In [67]:
np.random.randint(1,6,10) #1~6숫자 10개 가져오기 

array([4, 4, 3, 4, 2, 1, 4, 1, 3, 3], dtype=int32)

In [68]:
np.random.randint(1,6,(4,3))

array([[4, 4, 1],
       [3, 2, 3],
       [4, 3, 2],
       [5, 5, 4]], dtype=int32)

In [69]:
#표준 정규 분포로 가져오기

In [70]:
#키 평균:170, 표준편차 : 10

In [73]:
np.random.normal(170,10,10)

array([188.27141528, 159.13496227, 180.58442093, 177.47165092,
       176.09917802, 169.22772246, 150.58733709, 173.4143471 ,
       188.62855135, 167.04769525])

In [74]:
np.random.normal(170,10,(3,4))

array([[174.78316506, 162.84809504, 182.37292927, 178.40388647],
       [177.24127279, 168.19840695, 171.52579187, 182.29942938],
       [172.72076888, 170.7507401 , 170.8681927 , 144.84645724]])

In [76]:
arr=np.arange(5)

In [77]:
np.random.shuffle(arr) # 데이터 순서 섞기

In [78]:
arr

array([1, 3, 2, 4, 0])

In [80]:
np.random.choice(arr,3) # 데이터 중에 일부 가져오기

array([3, 4, 4])

In [81]:
np.random.choice(arr,arr.size)

array([1, 3, 2, 2, 0])

In [82]:
np.random.choice(arr,arr.size)

array([3, 0, 4, 1, 2])

In [83]:
#단위행렬 -> 대각선의 값이 1인것, 나머지는 0

In [85]:
# 3*1 = 3
# 3*0 = 0

In [87]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
#대각 행령 만들기 

In [90]:
np.diag([5,1,2,9]) #내가 원하는 값을 대각선에 넣는 함수

array([[5, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 9]])

In [91]:
# 데이터 타입 확인

In [92]:
temp.dtype

dtype('float64')

In [93]:
#사이즈 확인

In [94]:
temp.size

5

In [95]:
np.info( temps)

class:  ndarray
shape:  (5,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x211bb7fa320
byteorder:  little
byteswap:  False
type: float64


In [96]:
sensor_data

array([[185.5, 186.2, 184.8],
       [120.3, 121.5, 119.8],
       [ 45.2,  44.8,  45.5]])

In [97]:
sensor_data[1,]

array([120.3, 121.5, 119.8])

In [99]:
sensor_data[1,0:2] #numpy에 경우 행렬 슬라이싱 가능

array([120.3, 121.5])

In [100]:
temps

array([185.5, 186.2, 184.8, 185. , 186.1])

In [102]:
temps[[1,3]]  #연속되지 않은 두개의 데이터 가져오는 법

array([186.2, 185. ])

In [104]:
sensor_data[ 1 , [0,2] ] # 2차원에서 연속되지 않은 두개의 데이터 가져오는 법

array([120.3, 119.8])

In [105]:
sensor_data[[0,1],2]

array([184.8, 119.8])

In [106]:
#Bollean Indexing

In [107]:
temps

array([185.5, 186.2, 184.8, 185. , 186.1])

In [110]:
temps > 186 #numpy만 가능한 것 (list는 안됨)

array([False,  True, False, False,  True])

In [114]:
temps[temps>186] # 반복문을 쓰지 않고도 바로 쓸 수 있다

array([186.2, 186.1])

In [123]:
temps[(185>temps) | (186<temps) ] #boolean 이 아니기 때문에 or,and,.... 을 사용할 수 없다 &,|

array([186.2, 184.8, 186.1])

In [125]:
temps

array([185.5, 186.2, 184.8, 185. , 186.1])

In [128]:
temps[1:4] =[186.5,184.5,185.5]  #인덱싱을 이용한 값 변경

In [129]:
temps

array([185.5, 186.5, 184.5, 185.5, 186.1])

In [130]:
temps[1:4] =0

In [131]:
temps

array([185.5,   0. ,   0. ,   0. , 186.1])

In [134]:
x=np.random.randint(0,100,20)

In [136]:
x

array([81, 39, 26, 64, 33, 31, 39, 11, 23, 51, 93, 70, 70, 48, 43, 62, 99,
       39, 82, 16], dtype=int32)

In [145]:
x[(x<20)|(x>85)] = 0 #해당되는 값만 변경

In [142]:
x

array([81, 39, 26, 64, 33, 31, 39,  1, 23, 51,  1, 70, 70, 48, 43, 62,  1,
       39, 82,  1], dtype=int32)

In [154]:
x=x.astype(np.float64) #타입 변경

In [155]:
x[(x<20.)|(x>85.)] = np.nan #해당되는 값만 변경 nan으로 변경

In [156]:
x

array([81., 39., 26., 64., 33., 31., 39., nan, 23., 51., nan, 70., 70.,
       48., 43., 62., nan, 39., 82., nan])

In [157]:
x=np.random.randint(0,100,20)

In [158]:
x

array([21, 38, 61, 67, 85, 96, 64, 87,  5, 43, 78,  0, 22, 82, 25, 88, 72,
       92, 57, 42], dtype=int32)

In [159]:
x.astype(np.float64)

array([21., 38., 61., 67., 85., 96., 64., 87.,  5., 43., 78.,  0., 22.,
       82., 25., 88., 72., 92., 57., 42.])

In [160]:
# 이상치를 이 데이터의 평균값으로 변경

In [162]:
x[(x<20.)|(x>85.)] = x.mean()

In [163]:
x

array([21, 38, 61, 67, 85, 56, 64, 56, 56, 43, 78, 56, 22, 82, 25, 56, 72,
       56, 57, 42], dtype=int32)

In [164]:
#형태 (차원) 변경

In [165]:
arr=np.arange(12)

In [167]:
arr.ndim  #차원 확인

1

In [169]:
arr.shape #형태 알아보기

(12,)

In [178]:
arr.reshape(1,12) #shape 바꾸기

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [179]:
arr.reshape(12,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [180]:
arr.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [184]:
arr.reshape(3,-1)  #-1을 자동으로 숫자를 정해줌

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [186]:
arr+2 #brodcasting

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [187]:
x

array([21, 38, 61, 67, 85, 56, 64, 56, 56, 43, 78, 56, 22, 82, 25, 56, 72,
       56, 57, 42], dtype=int32)

In [189]:
np.argmax(x) #최댓값의 인덱스

np.int64(4)

In [191]:
np.argmin(x) # 최솟값의 인덱스

np.int64(0)

In [194]:
np.std(x) # 표준 편차

np.float64(17.975747550519284)

In [195]:
np.sum(x)

np.int64(1093)

In [196]:
np.min(x)

np.int32(21)

In [197]:
np.max(x)

np.int32(85)

In [200]:
X=np.random.randint(1,100,(4,5))

In [202]:
X #가로는 axis =0/ 세로는 axis =1

array([[22, 80, 31, 81, 16],
       [ 8, 68, 80, 86, 41],
       [10, 67, 82, 33, 52],
       [20, 93, 40, 77, 56]], dtype=int32)

In [205]:
X.max(axis=1)

array([81, 86, 82, 93], dtype=int32)

In [206]:
#사분위 수

In [207]:
data = [5,4,1,9,3,2,2]

In [208]:
sorted(data)

[1, 2, 2, 3, 4, 5, 9]

In [209]:
data = np.array(data)

In [212]:
np.median(data) #중앙값 뽑기

np.float64(3.0)

In [213]:
np.percentile(data,75)

np.float64(4.5)

In [215]:
np.percentile(data,[25,50,75] )


array([2. , 3. , 4.5])

In [216]:
#이상치 탑지(IQR 방법

In [ ]:
np.random.radint(180,